<?php
/**
 * @file
 * Module file for DBCDK Community.
 */

/**
 * Implements hook_user_login().
 */
function dbcdk_community_user_login(\Drupal\user\Entity\User $account) {
  // Redirect moderators to the flagged content list.
  if (in_array('admin_moderator', $account->getRoles())) {
    $url = new \Drupal\Core\Url('page_manager.page_view_dbcdk_community_flagged_content');
    $redirect = new \Symfony\Component\HttpFoundation\RedirectResponse($url->toString());
    $redirect->send();
  }
}

/**
 * Implements hook_theme().
 */
function dbcdk_community_theme($existing, $type, $theme, $path) {
  return [
    'dbcdk_community__flagged_content__content' => [
      'variables' => [
        'content' => NULL,
        'image_collection_count' => NULL,
        'video_collection_count' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_element_info_alter().
 *
 * Add our own library to the toolbar so we can define icons for custom links.
 */
function dbcdk_community_element_info_alter(array &$types) {
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'dbcdk_community/toolbar';
  }
}

/**
 * Implements hook_toolbar_alter().
 *
 * Remove the "home" item since we don't have any front-end to direct the user
 * back to.
 */
function dbcdk_community_toolbar_alter(&$items) {
  if (isset($items['home'])) {
    unset($items['home']);
  }
}

/**
 * Implements hook_link_alter().
 */
function dbcdk_community_link_alter(&$variables) {
  // Make all external links open in a new window.
  /* @var \Drupal\Core\Url $url */
  $url = $variables['url'];
  if ($url->isExternal()) {
    $variables['options']['attributes']['target'] = '_blank';
  }
}
