<?php
/**
 * FileContainerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace DBCDK\CommunityServices\Api;

use \DBCDK\CommunityServices\Configuration;
use \DBCDK\CommunityServices\ApiClient;
use \DBCDK\CommunityServices\ApiException;
use \DBCDK\CommunityServices\ObjectSerializer;

/**
 * FileContainerApiTest Class Doc Comment
 *
 * @category Class
 * @package  DBCDK\CommunityServices
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FileContainerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for fileContainerFind
     *
     * Find all instances of the model matched by filter from the data source.
     *
     */
    public function test_fileContainerFind() {

    }
    
    /**
     * Test case for fileContainerUpsert
     *
     * Update an existing model instance or insert a new one into the data source.
     *
     */
    public function test_fileContainerUpsert() {

    }
    
    /**
     * Test case for fileContainerCreate
     *
     * Create a new instance of the model and persist it into the data source.
     *
     */
    public function test_fileContainerCreate() {

    }
    
    /**
     * Test case for fileContainerCreateChangeStreamGetFileContainersChangeStream
     *
     * Create a change stream.
     *
     */
    public function test_fileContainerCreateChangeStreamGetFileContainersChangeStream() {

    }
    
    /**
     * Test case for fileContainerCreateChangeStreamPostFileContainersChangeStream
     *
     * Create a change stream.
     *
     */
    public function test_fileContainerCreateChangeStreamPostFileContainersChangeStream() {

    }
    
    /**
     * Test case for fileContainerCount
     *
     * Count instances of the model matched by where from the data source.
     *
     */
    public function test_fileContainerCount() {

    }
    
    /**
     * Test case for fileContainerFindOne
     *
     * Find first instance of the model matched by filter from the data source.
     *
     */
    public function test_fileContainerFindOne() {

    }
    
    /**
     * Test case for fileContainerUpdateAll
     *
     * Update instances of the model matched by where from the data source.
     *
     */
    public function test_fileContainerUpdateAll() {

    }
    
    /**
     * Test case for fileContainerGetContainer
     *
     * 
     *
     */
    public function test_fileContainerGetContainer() {

    }
    
    /**
     * Test case for fileContainerDestroyContainer
     *
     * 
     *
     */
    public function test_fileContainerDestroyContainer() {

    }
    
    /**
     * Test case for fileContainerDownload
     *
     * 
     *
     */
    public function test_fileContainerDownload() {

    }
    
    /**
     * Test case for fileContainerGetFiles
     *
     * 
     *
     */
    public function test_fileContainerGetFiles() {

    }
    
    /**
     * Test case for fileContainerGetFile
     *
     * 
     *
     */
    public function test_fileContainerGetFile() {

    }
    
    /**
     * Test case for fileContainerRemoveFile
     *
     * 
     *
     */
    public function test_fileContainerRemoveFile() {

    }
    
    /**
     * Test case for fileContainerUpload
     *
     * 
     *
     */
    public function test_fileContainerUpload() {

    }
    
    /**
     * Test case for fileContainerFindById
     *
     * Find a model instance by id from the data source.
     *
     */
    public function test_fileContainerFindById() {

    }
    
    /**
     * Test case for fileContainerExistsHeadFileContainersid
     *
     * Check whether a model instance exists in the data source.
     *
     */
    public function test_fileContainerExistsHeadFileContainersid() {

    }
    
    /**
     * Test case for fileContainerPrototypeUpdateAttributes
     *
     * Update attributes for a model instance and persist it into the data source.
     *
     */
    public function test_fileContainerPrototypeUpdateAttributes() {

    }
    
    /**
     * Test case for fileContainerDeleteById
     *
     * Delete a model instance by id from the data source.
     *
     */
    public function test_fileContainerDeleteById() {

    }
    
    /**
     * Test case for fileContainerExistsGetFileContainersidExists
     *
     * Check whether a model instance exists in the data source.
     *
     */
    public function test_fileContainerExistsGetFileContainersidExists() {

    }
    
}
